apiVersion: v1
kind: Service
metadata:
  name: counter-service
  labels:
    app: counter-service
    service: counter-service
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: counter-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ep-counter
  labels:
    app: counter-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-service
      version: v1
  template:
    metadata:
      labels:
        app: counter-service
        version: v1
    spec:
          restartPolicy: Always
          imagePullSecrets:
            - name: image-pull-secret  #added
          containers:
          - name: ep-counter
            image: tarun00000/ep-hit-counter:v1.2.0
            ports:
              - containerPort: 9080

