# It will apply MTLS to all services in default namespace.
# It overrides meshpolicy
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: default
  namespace: default
spec:
  peers:
  - mtls: {}
