apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: redis-cron
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: image-pull-secret  #added
          containers:
          - name: redis-cron
            image: tarun00000/redis-go:v2.1.0